// examples/shadcn/MegaNav.tsx
"use client";

/**
 * shadcn/ui — built on the NavigationMenu component, which brings the keyboard
 * navigation, focus management and ARIA wiring for free (it wraps Radix's
 * primitive).
 *
 * ```bash
 * npx shadcn@latest add navigation-menu
 * ```
 *
 * Items come in as a prop; fetch them in a server component (see the next/
 * template) so the token stays on the server.
 */
import * as React from "react";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
} from "@/components/ui/navigation-menu";
import { cn } from "@/lib/utils";
import {
  effectiveLayout,
  image,
  linkProps,
  text,
  type NavItem,
} from "../mega-nav";

/**
 * `asChild` hands NavigationMenuLink's behaviour to our own anchor — that is the
 * documented way to keep the menu's keyboard and focus semantics while
 * controlling the markup. Swap `<a>` for `next/link` if you prefer.
 */
function MenuLink({
  item,
  className,
  children,
}: {
  item: NavItem;
  className?: string;
  children?: React.ReactNode;
}) {
  const props = linkProps(item);
  const content = children ?? item.title;

  if (!props) {
    return <span className={cn("block", className)}>{content}</span>;
  }
  return (
    <NavigationMenuLink asChild>
      <a
        {...props}
        className={cn(
          "block select-none rounded-md p-3 leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent",
          className,
        )}
      >
        {content}
      </a>
    </NavigationMenuLink>
  );
}

function LinkWithDescription({ item }: { item: NavItem }) {
  const description = text(item, "description");
  return (
    <MenuLink item={item}>
      <span className="text-sm font-medium">{item.title}</span>
      {description ? (
        <span className="mt-1 line-clamp-2 block text-sm text-muted-foreground">
          {description}
        </span>
      ) : null}
    </MenuLink>
  );
}

function SimplePanel({ item }: { item: NavItem }) {
  return (
    <ul className="grid w-[320px] gap-1 p-3">
      {item.children.map((child) => (
        <li key={child.id}>
          <LinkWithDescription item={child} />
        </li>
      ))}
    </ul>
  );
}

function ColumnsPanel({ item }: { item: NavItem }) {
  const visual = image(item);
  const headline = text(item, "description");

  return (
    <div className="flex w-[860px] gap-6 p-5">
      <div className="grid flex-1 grid-cols-3 gap-x-6 gap-y-5">
        {item.children.map((group) => (
          <div
            key={group.id}
            className={cn(
              "rounded-lg",
              group.fields.highlight === true && "bg-accent/40 p-3 ring-1 ring-border",
            )}
          >
            <p className="mb-2 px-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
              {group.title}
            </p>
            <ul className="space-y-1">
              {group.children.map((link) => (
                <li key={link.id}>
                  <LinkWithDescription item={link} />
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      {visual || headline ? (
        <aside className="w-60 shrink-0 rounded-lg bg-muted p-4">
          {visual ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={visual.url}
              alt={visual.alternativeText ?? ""}
              className="mb-3 h-28 w-full rounded-md object-cover"
            />
          ) : null}
          {headline ? <p className="font-semibold leading-snug">{headline}</p> : null}
          {text(item, "tagline") ? (
            <p className="mt-1 text-sm text-muted-foreground">{text(item, "tagline")}</p>
          ) : null}
          {text(item, "ctaLabel") && text(item, "ctaUrl") ? (
            <a
              href={text(item, "ctaUrl")}
              className="mt-3 inline-block text-sm font-semibold underline"
            >
              {text(item, "ctaLabel")}
            </a>
          ) : null}
        </aside>
      ) : null}
    </div>
  );
}

const PANELS: Record<string, React.ComponentType<{ item: NavItem }>> = {
  simple: SimplePanel,
  columns: ColumnsPanel,
  split: ColumnsPanel,
  banner: ColumnsPanel,
};

export function MegaNav({ items }: { items: NavItem[] }) {
  return (
    <NavigationMenu>
      <NavigationMenuList>
        {items.map((item) => {
          const Panel = PANELS[effectiveLayout(item)] ?? SimplePanel;
          return (
            <NavigationMenuItem key={item.id}>
              {item.children.length ? (
                <>
                  <NavigationMenuTrigger>{item.title}</NavigationMenuTrigger>
                  <NavigationMenuContent>
                    <Panel item={item} />
                  </NavigationMenuContent>
                </>
              ) : (
                <MenuLink item={item} className="px-4 py-2 text-sm font-medium" />
              )}
            </NavigationMenuItem>
          );
        })}
      </NavigationMenuList>
    </NavigationMenu>
  );
}

export default MegaNav;

// examples/nuxt/MegaNav.vue
<script setup lang="ts">
/**
 * Nuxt — the header component. Put this in `components/MegaNav.vue` and use it
 * as `<MegaNav slug="main-navigation" />`.
 *
 * It reads the server route from the sibling template, so the token never
 * reaches the browser. The slug and locale are reactive: switching language
 * refetches.
 */
import {
  effectiveLayout,
  image,
  linkProps,
  text,
  type NavItem,
} from "../mega-nav";

const props = withDefaults(defineProps<{ slug?: string }>(), {
  slug: "main-navigation",
});

const { locale } = useI18n?.() ?? { locale: ref(undefined) };

const { data: items } = await useFetch<NavItem[]>(
  () => `/api/navigation/${props.slug}`,
  { query: { locale }, default: () => [] },
);

const open = ref<string | null>(null);
</script>

<template>
  <nav aria-label="Main">
    <ul class="flex items-center gap-1">
      <li
        v-for="item in items"
        :key="item.id"
        class="relative"
        @mouseenter="open = item.id"
        @mouseleave="open = null"
      >
        <!-- No children: a plain link (or a heading when it has no target). -->
        <component
          v-if="!item.children.length"
          :is="linkProps(item) ? 'a' : 'span'"
          v-bind="linkProps(item) ?? {}"
          class="px-3 py-2 text-sm font-medium"
        >
          {{ item.title }}
        </component>

        <template v-else>
          <button
            type="button"
            :aria-expanded="open === item.id"
            class="px-3 py-2 text-sm font-medium"
            @click="open = open === item.id ? null : item.id"
          >
            {{ item.title }}
          </button>

          <div
            v-if="open === item.id"
            class="absolute left-0 top-full z-50 rounded-xl border bg-white shadow-xl"
          >
            <!-- Grouped layouts: level 2 = groups, level 3 = links. -->
            <div
              v-if="['columns', 'split', 'banner'].includes(effectiveLayout(item))"
              class="flex gap-8 p-6"
            >
              <div class="grid flex-1 grid-cols-2 gap-x-8 gap-y-6 md:grid-cols-4">
                <div
                  v-for="group in item.children"
                  :key="group.id"
                  :class="group.fields.highlight === true && 'rounded-lg p-3 ring-1 ring-current/20'"
                >
                  <p class="mb-2 text-xs font-semibold uppercase tracking-wide opacity-50">
                    {{ group.title }}
                  </p>
                  <ul class="space-y-2">
                    <li
                      v-for="link in group.children"
                      :key="link.id"
                    >
                      <!-- Description inside the link: the whole block clicks. -->
                      <component
                        :is="linkProps(link) ? 'a' : 'span'"
                        v-bind="linkProps(link) ?? {}"
                        class="block text-sm hover:underline"
                      >
                        <span class="block font-medium">{{ link.title }}</span>
                        <span
                          v-if="text(link, 'description')"
                          class="mt-0.5 block text-xs opacity-60"
                        >
                          {{ text(link, 'description') }}
                        </span>
                      </component>
                    </li>
                  </ul>
                </div>
              </div>

              <aside
                v-if="image(item) || text(item, 'description')"
                class="w-56 shrink-0 rounded-xl bg-black/5 p-4"
              >
                <img
                  v-if="image(item)"
                  :src="image(item)!.url"
                  :alt="image(item)!.alternativeText ?? ''"
                  class="mb-3 h-24 w-full rounded-lg object-cover"
                >
                <p
                  v-if="text(item, 'description')"
                  class="font-semibold"
                >
                  {{ text(item, 'description') }}
                </p>
                <a
                  v-if="text(item, 'ctaLabel') && text(item, 'ctaUrl')"
                  :href="text(item, 'ctaUrl')"
                  class="mt-3 inline-block text-sm font-semibold underline"
                >
                  {{ text(item, 'ctaLabel') }}
                </a>
              </aside>
            </div>

            <!-- Everything else: a flat list. -->
            <ul
              v-else
              class="min-w-48 space-y-2 p-4"
            >
              <li
                v-for="child in item.children"
                :key="child.id"
              >
                <component
                  :is="linkProps(child) ? 'a' : 'span'"
                  v-bind="linkProps(child) ?? {}"
                  class="text-sm hover:underline"
                >
                  {{ child.title }}
                </component>
              </li>
            </ul>
          </div>
        </template>
      </li>
    </ul>
  </nav>
</template>
